/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Job;

import Business.CourseCatalog.CourseCatalog;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Food.Food;
import Business.Organization.JobTrainerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEHA
 */
public class AddCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCoursesJPanel
     */
   
JPanel userProcessContainer; UserAccount account; Enterprise enterprise; Ecosystem business; JobTrainerOrganization jobTrainerOrganization;
    public  AddCoursesJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Ecosystem business, JobTrainerOrganization jobTrainerOrganization) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.enterprise=enterprise;
       this.business=business;
       this.jobTrainerOrganization=jobTrainerOrganization;
       populateCourseCatalogTable();
    }
    public void populateCourseCatalogTable (){
    DefaultTableModel model = (DefaultTableModel) tblCourseCatalog.getModel();

        model.setRowCount(0);
             for(CourseCatalog courseCatalog: jobTrainerOrganization.getCourseCatalogDirectory().getCourseCatalogList()){
            Object[] row = new Object[3];
            row[0] = courseCatalog;
            row[1] = courseCatalog.getBudget();
             row[2] = courseCatalog.getCourseCategory();
              
               model.addRow(row);
        }
}
    
        
    /**
     * This method is called 
     * 
     * 
     * 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCoursePrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseCatalog = new javax.swing.JTable();
        btnADDCOURSE = new javax.swing.JButton();
        courseCategoryCB = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Course Name");

        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Expected Salary");

        txtCoursePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoursePriceActionPerformed(evt);
            }
        });

        jLabel3.setText("Course Category");

        tblCourseCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Budget", "Course Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseCatalog);

        btnADDCOURSE.setText("Add Course");
        btnADDCOURSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDCOURSEActionPerformed(evt);
            }
        });

        courseCategoryCB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        courseCategoryCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hospitality", "Finance", "Retail", "Technology", "Medicine", "Management" }));
        courseCategoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCategoryCBActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnADDCOURSE)
                        .addGap(65, 65, 65)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseCategoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(courseCategoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADDCOURSE)
                    .addComponent(btnBack))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCoursePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoursePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoursePriceActionPerformed

    private void btnADDCOURSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDCOURSEActionPerformed
        // TODO add your handling code here:
        /*String transportName = txtFoodName.getText();
        int transportPrice = Integer.parseInt(txtFoodPrice.getText());
        String transportType = (String) transportCB.getSelectedItem();

        String transportID = txtTransID.getText();
        String transportRoute = txtTransRoute.getText();
        Organization org=null;
       for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof TransportOrganization){
                org=organization;
                break;
            }
        }

        if(org!=null){
            System.out.println(org);
            org.getTransportNamesDirectory().addTransport(transportName,transportID,transportRoute,transportType,transportPrice);

        }
        populateTransportTable();*/
        try{
        String courseCatalogName = txtCourseName.getText();
        int budget = Integer.parseInt(txtCoursePrice.getText());
        String courseType= (String) courseCategoryCB.getSelectedItem();
JOptionPane.showMessageDialog(null, "Courses added successfully!");
      jobTrainerOrganization.getCourseCatalogDirectory().addCourseCatalog(courseCatalogName,courseType,budget);
      populateCourseCatalogTable();
      }
        catch(Exception e){
       JOptionPane.showMessageDialog(null,"Enter valid input");
       System.out.println(e);
        }
    }//GEN-LAST:event_btnADDCOURSEActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void courseCategoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCategoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseCategoryCBActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDCOURSE;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox courseCategoryCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseCatalog;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCoursePrice;
    // End of variables declaration//GEN-END:variables
}
