/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Job;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Job.Job;
import Business.JobWorkQueue.JobFinderWorkRequest;
import Business.Organization.JobFinderOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nupur
 */
public class ApplyingJobPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindingPanel
     */
   JPanel userProcessContainer; UserAccount account; JobFinderOrganization jobFinderOrganization; Enterprise enterprise; Ecosystem business; Job job;JobFinderWorkRequest request;
    ApplyingJobPanel(JPanel userProcessContainer, UserAccount account, JobFinderOrganization jobFinderOrganization, Enterprise enterprise, Ecosystem business, Job job,JobFinderWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.jobFinderOrganization=jobFinderOrganization;
        this.enterprise=enterprise;
        this.business=business;
        this.job=job;
        this.request=request;
        fillTexts();
    }    
     public void fillTexts(){
          
           txtJobName.setText(job.getJobName());
          txtJobCost.setText(String.valueOf(job.getJobSalary()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtJobName = new javax.swing.JTextField();
        btnApplyForJob = new javax.swing.JButton();
        btnNotify = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtJobCost = new javax.swing.JTextField();
        BtnSendToJobTracker = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Job Salary: ");

        txtJobName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobNameActionPerformed(evt);
            }
        });

        btnApplyForJob.setText("APPLY FOR JOB ");
        btnApplyForJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyForJobActionPerformed(evt);
            }
        });

        btnNotify.setText("NOTIFY IF JOB STATUS IS ACCEPTED");
        btnNotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotifyActionPerformed(evt);
            }
        });

        jLabel3.setText("Job Name: ");

        txtJobCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobCostActionPerformed(evt);
            }
        });

        BtnSendToJobTracker.setText("NOTIFY JOB TRACKER");
        BtnSendToJobTracker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendToJobTrackerActionPerformed(evt);
            }
        });

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSendToJobTracker)
                        .addGap(176, 176, 176)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNotify)
                    .addComponent(btnApplyForJob)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJobCost, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJobName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJobName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJobCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnApplyForJob)
                .addGap(37, 37, 37)
                .addComponent(btnNotify)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSendToJobTracker)
                    .addComponent(btnBack1))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtJobNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobNameActionPerformed

    private void btnApplyForJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyForJobActionPerformed
        // TODO add your handling code here:
        int index =business.getMotherDirectory().getMotherIndex(request.getMotherNmae()); 
        business.getMotherDirectory().getMotherList().get(index).setJobApplicationStatus("Applied");
        JOptionPane.showMessageDialog(null,"Applied !!!!");
    }//GEN-LAST:event_btnApplyForJobActionPerformed

    private void btnNotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifyActionPerformed
        // TODO add your handling code here:
        //AcceptedJobJPanel
           int index =business.getMotherDirectory().getMotherIndex(request.getMotherNmae()); 
        business.getMotherDirectory().getMotherList().get(index).setJobApplicationStatus("Done");
         business.getMotherDirectory().getMotherList().get(index).setJobStatus("Congratulations!!You have been selected!");
         
    }//GEN-LAST:event_btnNotifyActionPerformed

    private void txtJobCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobCostActionPerformed

    private void BtnSendToJobTrackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendToJobTrackerActionPerformed
         
          int index =business.getMotherDirectory().getMotherIndex(request.getMotherNmae());
          if( business.getMotherDirectory().getMotherList().get(index).getJobStatus().equalsIgnoreCase("Congratulations!!You have been selected!")){
               String motherName= request.getMotherNmae();
        RequestTrackerJPanel requestTrackerPanel = new RequestTrackerJPanel(userProcessContainer, account, jobFinderOrganization, enterprise, business,job,motherName);
        userProcessContainer.add("requestTrackerPanel", requestTrackerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    } else
          {
           JOptionPane.showMessageDialog(null," Candidate has not been selected for job!!");
                  }
        /*TrackerWorkRequest twr = new TrackerWorkRequest();

        // twr.setMessage(TxtMessage.getText());

        twr.setSender(account);
        twr.setStatus("Sent");
        Organization org = null;

        for (Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof TrackerOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getJobWorkQueue().getTrackerWorkRequestList().add(twr);
            account.getJobWorkQueue().getTrackerWorkRequestList().add(twr);
        }
        populateTable();*/
    }//GEN-LAST:event_BtnSendToJobTrackerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSendToJobTracker;
    private javax.swing.JButton btnApplyForJob;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnNotify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtJobCost;
    private javax.swing.JTextField txtJobName;
    // End of variables declaration//GEN-END:variables
}
