/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Job;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.JobWorkQueue.JobFinderWorkRequest;
import Business.JobWorkQueue.JobTrainerWorkRequest;
import Business.Mother.Mother;
import Business.Organization.JobFinderOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class CompletionCourses extends javax.swing.JPanel {

    /**
     * Creates new form CompletionCourses
     */
   
JPanel userProcessContainer; Enterprise enterprise; JobTrainerWorkRequest request;
UserAccount account;
String courseName;
String name; Ecosystem business;
public CompletionCourses(JPanel userProcessContainer, Enterprise enterprise, JobTrainerWorkRequest request, UserAccount account, String courseName, String name, Ecosystem business) {
       initComponents();
this.userProcessContainer=userProcessContainer;
this.enterprise=enterprise;
this.request=request;
this.account=account;
this.courseName=courseName;
this.name=name;
this.business=business;
populateTable();
txtName.setText(name);
txtCourseTaken.setText(courseName);
}

   

       
public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (JobTrainerWorkRequest request : account.getJobWorkQueue().getTrainerWorkRequestList()) {
            if (request instanceof JobFinderWorkRequest) {
                Object[] row = new Object[9];
                row[0] = request;
                row[1] = request.getMotherNmae();
                row[2] = request.getCourseTaken();
                row[3] = request.getMotherStatus();
                row[4] =  request.getCourseGrades();
                row[5] = request.getSender().getEmployee().getName();
                row[6] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[7] = request.getStatus();
                row[8] = ((JobFinderWorkRequest) request).getResult();

                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        BtnRequestFinder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtCourseTaken = new javax.swing.JTextField();
        txtGrades = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Name");

        jLabel2.setText("Course Taken");

        jLabel4.setText("Status of course");

        jLabel5.setText("Course Grades");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        BtnRequestFinder.setText("Send to Jobfinder");
        BtnRequestFinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestFinderActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Name", "Course Taken", "Status of Course", "Course Grades", "Sender", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        txtName.setEditable(false);

        txtCourseTaken.setEditable(false);

        txtGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradesActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Complete", "Incomplete" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtCourseTaken)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrades))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(BtnRequestFinder, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterpriseLabel)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtCourseTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(btnSave)
                .addGap(30, 30, 30)
                .addComponent(BtnRequestFinder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRequestFinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestFinderActionPerformed
      if(cbStatus.getSelectedItem().toString().equals("Complete")){
         
      
         JobFinderWorkRequest wr = new JobFinderWorkRequest();
        wr.setMotherNmae(txtName.getText());
        wr.setCourseGrades(txtGrades.getText());
        wr.setCourseTaken(txtCourseTaken.getText());
        wr.setMotherStatus(cbStatus.getSelectedItem().toString());
        wr.setSender(account);
        wr.setStatus("Sent");
        wr.setMessage("This candidate is being sent to you for job search!");
        Organization org = null;
        
        for (Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof JobFinderOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            org.getJobWorkQueue().getTrainerWorkRequestList().add(wr);
            account.getJobWorkQueue().getTrainerWorkRequestList().add(wr);
        }
        populateTable();
      }
      else  JOptionPane.showMessageDialog(null,"You can send this request to the job finder! Mother needs to complete her course!");
      
    }//GEN-LAST:event_BtnRequestFinderActionPerformed

    private void txtGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradesActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //save all the data to eneterprise level 
        //go to jobFinderJpanel
        try{
          for(Mother mother :business.getMotherDirectory().getMotherList()){
       if(mother.getName().equals(request.getMotherName())){    
       
       
         int index =business.getMotherDirectory().getMotherIndex(mother.getName());
         
        business.getMotherDirectory().getMotherList().get(index).setCourseGrade(txtGrades.getText());
           if (cbStatus.getSelectedItem() != null){
          String status = (String)cbStatus.getSelectedItem();
           JOptionPane.showMessageDialog(null, "Saved successfully!");
         business.getMotherDirectory().getMotherList().get(index).setCourseStatus(status);
           }
           else JOptionPane.showMessageDialog(null,"Select a row!");
           
       }}
           }
        catch(Exception e){
       JOptionPane.showMessageDialog(null,"Enter valid input");
       System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRequestFinder;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCourseTaken;
    private javax.swing.JTextField txtGrades;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
