/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Job;

import Business.CourseCatalog.CourseCatalog;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.JobWorkQueue.JobTrainerWorkRequest;
import Business.Mother.Mother;
import Business.Organization.JobTrainerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class CoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoursesJPanel
     */
     SimpleDateFormat dateFormat = new SimpleDateFormat("mm-dd-yyyy");
   JPanel userProcessContainer; UserAccount account; Enterprise enterprise; Ecosystem business; JobTrainerOrganization jobTrainerOrganization;JobTrainerWorkRequest request;
    CoursesJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Ecosystem business, JobTrainerOrganization jobTrainerOrganization,JobTrainerWorkRequest request) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.enterprise=enterprise;
       this.account=account;
       this.business=business;
       this.jobTrainerOrganization=jobTrainerOrganization;
       this.request=request;
       populateFields();
       System.out.println(request.getMotherName());
    }
   public void populateFields(){
       
       for(Mother mother :business.getMotherDirectory().getMotherList()){
           System.out.println(mother.getName());
       if(mother.getName().equals(request.getMotherName())){    
       
       
         int index =business.getMotherDirectory().getMotherIndex(mother.getName());
        txtxFoi.setText(business.getMotherDirectory().getMotherList().get(index).getFieldOfInterest());
        txtAptitude2.setText(String.valueOf(business.getMotherDirectory().getMotherList().get(index).getAptitudeScore()));
       txtName.setText(business.getMotherDirectory().getMotherList().get(index).getName());
        txtDreamSalary.setText(String.valueOf(business.getMotherDirectory().getMotherList().get(index).getDreamJobSal()));
   }}}
   public void populateCoursesBox(){
       DefaultTableModel model = (DefaultTableModel) tblCourseName.getModel();

        model.setRowCount(0);
         for(CourseCatalog courseCatalog :jobTrainerOrganization.getCourseCatalogDirectory().getCourseCatalogList()){
           if(courseCatalog.getCourseCategory().equalsIgnoreCase(txtxFoi.getText()) && courseCatalog.getBudget()<=Float.parseFloat((txtDreamSalary.getText()))){
            
                        Object[] row = new Object[1];
            row[0] =courseCatalog;
            
               model.addRow(row);  
             
           }
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtxFoi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDreamSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        btnSel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bnConfirm = new javax.swing.JButton();
        txtEndDate = new javax.swing.JTextField();
        txtAptitude2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseName = new javax.swing.JTable();
        btnBack1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Field Of Interest");

        txtxFoi.setEditable(false);

        jLabel3.setText("Select Courses");

        jLabel4.setText("Dream Salary");

        txtDreamSalary.setEditable(false);
        txtDreamSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDreamSalaryActionPerformed(evt);
            }
        });

        jLabel5.setText("Aptitude");

        btnSel.setText("Select Courses");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });

        jLabel6.setText("Name");

        txtName.setEditable(false);

        jLabel7.setText("Start Date");

        jLabel8.setText("End Date");

        bnConfirm.setText("Confirm");
        bnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnConfirmActionPerformed(evt);
            }
        });

        txtAptitude2.setEditable(false);

        tblCourseName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Courses Names"
            }
        ));
        jScrollPane2.setViewportView(tblCourseName);

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnSel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtxFoi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDreamSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAptitude2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnConfirm)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtxFoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtDreamSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAptitude2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnSel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBack1)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnConfirm)
                        .addGap(99, 99, 99))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDreamSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDreamSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDreamSalaryActionPerformed

    private void bnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnConfirmActionPerformed
        // TODO add your handling code here:
       // CompletionCourses cc= 
       try{
       int selectedRow = tblCourseName.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }

        CourseCatalog courseCatalog = (CourseCatalog) tblCourseName.getValueAt(selectedRow, 0);

       for(Mother mother :business.getMotherDirectory().getMotherList()){
       if(mother.getName().equals(request.getMotherName())){    
       
       
         int index =business.getMotherDirectory().getMotherIndex(mother.getName());
          
         business.getMotherDirectory().getMotherList().get(index).setCourseName(courseCatalog.getCourseName());
            String courseName =business.getMotherDirectory().getMotherList().get(index).getCourseName();
            String name =business.getMotherDirectory().getMotherList().get(index).getName();
         
               business.getMotherDirectory().getMotherList().get(index).setsDate(dateFormat.parse(txtStartDate.getText()));
           
        
               business.getMotherDirectory().getMotherList().get(index).seteDate(dateFormat.parse(txtEndDate.getText()));
          
       CompletionCourses dsjp = new CompletionCourses (userProcessContainer, enterprise,request,account,courseName,name,business);
        userProcessContainer.add("CompletionCourses ", dsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
       
       }}
        JOptionPane.showMessageDialog(null, "BabySiting Employee created successfully!");
    }                                         
  catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter valid inputs");
            System.out.println(e);
        }
    }//GEN-LAST:event_bnConfirmActionPerformed

    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        // TODO add your handling code here:
        
        //for(CourseCatalog cc :jobTrainerOrganization.getCourseCatalogDirectory().getCourseCatalogList()){
            //if(cc.getCourseCategory().equalsIgnoreCase(txtxFoi.getText()) && cc.getBudget()<Float.parseFloat(txtDreamSalary.getText())){
                populateCoursesBox();
            //}
        //}
    }//GEN-LAST:event_btnSelActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnConfirm;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblCourseName;
    private javax.swing.JTextField txtAptitude2;
    private javax.swing.JTextField txtDreamSalary;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtxFoi;
    // End of variables declaration//GEN-END:variables
}
