/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Job;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.JobWorkQueue.JobFinderWorkRequest;
import Business.JobWorkQueue.TrackerWorkRequest;
import Business.Organization.TrackerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class JobTrackerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JobTrackerJPanel
     */
 
JPanel userProcessContainer; UserAccount account;TrackerOrganization trackerOrganization; Enterprise enterprise; Ecosystem business;
    public JobTrackerJPanel(JPanel userProcessContainer, UserAccount account, TrackerOrganization trackerOrganization, Enterprise enterprise, Ecosystem business) {
       initComponents();
       
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.trackerOrganization=trackerOrganization;
       this.enterprise=enterprise;
       this.business=business;
        valueLabel.setText(business.getName());
        populateTracker1();
    }
    public void populateTheLabels(){
        int selectedRow = workRequestJTable1.getSelectedRow();
          if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }
         JobFinderWorkRequest request = (JobFinderWorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
          int index =business.getMotherDirectory().getMotherIndex(request.getMotherName());
          lblFoodName.setText(business.getMotherDirectory().getMotherList().get(index).getFoodName());
          lblFoodPrice.setText(business.getMotherDirectory().getMotherList().get(index).getFoodPrice());
           lblHouseName.setText(business.getMotherDirectory().getMotherList().get(index).getHouseName());
          lblHousePrice.setText(business.getMotherDirectory().getMotherList().get(index).getHousePrice());
           lblTransName.setText(business.getMotherDirectory().getMotherList().get(index).getTransName());
          lblTransPrice.setText(business.getMotherDirectory().getMotherList().get(index).getTransPrice());
    }
 public void populateTracker1(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();

        model.setRowCount(0);

        for (JobFinderWorkRequest request1 : trackerOrganization.getJobWorkQueue().getFinderWorkRequestList()) {
            
//                 System.out.println("love"+request1.getJobName());
                Object[] row = new Object[8];
                row[0] = request1;
                row[1] = request1.getMotherName();
                row[2] = request1.getJobName();
                row[3] = request1.getJobSalary();
                row[4] =  request1.getSender().getEmployee().getName(); 
                row[5] =  request1.getReceiver() == null ? null : request1.getReceiver().getEmployee().getName();
                row[6] = request1.getStatus();
                row[7] = ((TrackerWorkRequest) request1).getResult();

                model.addRow(row);
            
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnTransport = new javax.swing.JButton();
        btnHousing = new javax.swing.JButton();
        btnFood = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        refreshTestJButton1 = new javax.swing.JButton();
        lblFoodName = new javax.swing.JLabel();
        lblFoodPrice = new javax.swing.JLabel();
        lblHouseName = new javax.swing.JLabel();
        lblHousePrice = new javax.swing.JLabel();
        lblTransName = new javax.swing.JLabel();
        lblTransPrice = new javax.swing.JLabel();
        btnFoodDetais = new javax.swing.JButton();
        btnTransportDetails = new javax.swing.JButton();
        btnHousingDetails = new javax.swing.JButton();
        btnRespose = new javax.swing.JButton();

        jButton1.setText("jButton1");

        btnTransport.setText("Transport Enterprise");
        btnTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportActionPerformed(evt);
            }
        });

        btnHousing.setText("Housing Enterprise");
        btnHousing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHousingActionPerformed(evt);
            }
        });

        btnFood.setText("Food Enterprise");
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Name", "Job received", "Salary", "Sender", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(workRequestJTable1);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueLabel.setText("<value>");

        refreshTestJButton1.setText("Refresh");
        refreshTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButton1ActionPerformed(evt);
            }
        });

        lblFoodName.setText("<Food Name>");

        lblFoodPrice.setText("<Food Price>");

        lblHouseName.setText("<Transprt Name>");

        lblHousePrice.setText("<Transport Price>");

        lblTransName.setText("<Housing Name>");

        lblTransPrice.setText("<Housing Price>");

        btnFoodDetais.setText("See Food Details");
        btnFoodDetais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodDetaisActionPerformed(evt);
            }
        });

        btnTransportDetails.setText("See Transport Details");
        btnTransportDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportDetailsActionPerformed(evt);
            }
        });

        btnHousingDetails.setText("See Housing Details");
        btnHousingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHousingDetailsActionPerformed(evt);
            }
        });

        btnRespose.setText("Respond to Finder");
        btnRespose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResposeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnRespose)
                                .addGap(34, 34, 34)
                                .addComponent(refreshTestJButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFood)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnHousing))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFoodDetais)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHousingDetails)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTransportDetails)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTransport)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFoodPrice)
                                    .addComponent(lblHouseName)
                                    .addComponent(lblHousePrice)
                                    .addComponent(lblTransName)
                                    .addComponent(lblTransPrice))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshTestJButton1)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseLabel)
                    .addComponent(btnRespose))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFoodName)
                .addGap(27, 27, 27)
                .addComponent(lblFoodPrice)
                .addGap(18, 18, 18)
                .addComponent(lblHouseName)
                .addGap(18, 18, 18)
                .addComponent(lblHousePrice)
                .addGap(18, 18, 18)
                .addComponent(lblTransName)
                .addGap(18, 18, 18)
                .addComponent(lblTransPrice)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFoodDetais)
                    .addComponent(btnTransportDetails)
                    .addComponent(btnHousingDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFood)
                    .addComponent(btnHousing)
                    .addComponent(btnTransport))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
        // TODO add your handling code here:
         int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }

        JobFinderWorkRequest request = (JobFinderWorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
       ProcessFoodJPanel pfjp = new ProcessFoodJPanel(userProcessContainer,account,trackerOrganization,enterprise,business,request);
         userProcessContainer.add("ProcessFoodJPanel", pfjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
        
    }//GEN-LAST:event_btnFoodActionPerformed

    private void btnTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }

        JobFinderWorkRequest request = (JobFinderWorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
        
        
        
          ProcessTransportJPanel ptjp = new ProcessTransportJPanel(userProcessContainer,account,trackerOrganization,enterprise,business,request);
         userProcessContainer.add("ProcessTransportJPanel", ptjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnTransportActionPerformed

    private void btnHousingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHousingActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }

        JobFinderWorkRequest request = (JobFinderWorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
        
          ProcessHousingJPanel phjp = new ProcessHousingJPanel(userProcessContainer,account,trackerOrganization,enterprise,business,request);
         userProcessContainer.add("ProcessHousingJPanel", phjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHousingActionPerformed

    private void refreshTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButton1ActionPerformed

        //   populateRequestTable1();
    }//GEN-LAST:event_refreshTestJButton1ActionPerformed

    private void btnFoodDetaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodDetaisActionPerformed
        // TODO add your handling code here:
        populateTheLabels();
    }//GEN-LAST:event_btnFoodDetaisActionPerformed

    private void btnTransportDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportDetailsActionPerformed
        // TODO add your handling code here:
         populateTheLabels();
    }//GEN-LAST:event_btnTransportDetailsActionPerformed

    private void btnHousingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHousingDetailsActionPerformed
        // TODO add your handling code here:
         populateTheLabels();
    }//GEN-LAST:event_btnHousingDetailsActionPerformed

    private void btnResposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResposeActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row!");
            return;
        }

        TrackerWorkRequest request = (TrackerWorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
        request.setResult("Request Recieved !!!!");
        request.setStatus("Processing");
        request.setReceiver(account);
        ResponseToFinder ResponseToFinder  = new ResponseToFinder(userProcessContainer, request,business);
        userProcessContainer.add("ResponseToFinder", ResponseToFinder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        
    }//GEN-LAST:event_btnResposeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFood;
    private javax.swing.JButton btnFoodDetais;
    private javax.swing.JButton btnHousing;
    private javax.swing.JButton btnHousingDetails;
    private javax.swing.JButton btnRespose;
    private javax.swing.JButton btnTransport;
    private javax.swing.JButton btnTransportDetails;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JLabel lblFoodPrice;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblHousePrice;
    private javax.swing.JLabel lblTransName;
    private javax.swing.JLabel lblTransPrice;
    private javax.swing.JButton refreshTestJButton1;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
