
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Housing;


import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Mother.Mother;
import Business.Organization.HousingOrganization;
import Business.Housing.HousingNames;
import Business.JobWorkQueue.HousingWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class BuyHousingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyHousingJPanel
     */
    
JPanel userProcessContainer; HousingOrganization housingOrganization; Enterprise enterprise;Ecosystem business;HousingWorkRequest request;
  public BuyHousingJPanel(JPanel userProcessContainer, HousingOrganization housingOrganization, Enterprise enterprise, HousingWorkRequest request, Ecosystem business) {
       initComponents();
       this.enterprise=enterprise;
       this.userProcessContainer=userProcessContainer;
       this.housingOrganization=housingOrganization;
       this.request=request;
        this.business=business;
       populateMotherTable();
       populateTransportTable();
       txtMotherName.setText(request.getMotherName());
       
    }

  
    
       
    public void populateMotherTable(){
        DefaultTableModel model = (DefaultTableModel) tblMother.getModel();

        model.setRowCount(0);
            for(Mother mother : business.getMotherDirectory().getMotherList()){
            Object[] row = new Object[2];
            row[0] = mother;
              row[1] = mother.getAge();
              //row[2] = mother.getMotherStatus();
               model.addRow(row);
        }
    }
     public void populateTransportTable(){
           DefaultTableModel model = (DefaultTableModel) tblHousing.getModel();

        model.setRowCount(0);
            for(HousingNames transportNames :housingOrganization.getHousingNamesDirectory().getHousingNames()){
            Object[] row = new Object[5];
            row[0] = transportNames;
              row[1] = transportNames.getPrice();
              row[2] = transportNames.getHousingType();
              row[3] = transportNames.getHousingID();
             row[4] = transportNames.getLocation();
               model.addRow(row);
        }
       } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMother = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHousing = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        txtHousingID = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtHousingPrice = new javax.swing.JTextField();
        txtHousingName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSelectMother = new javax.swing.JButton();
        btnHousing = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        tblMother.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblMother);

        tblHousing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Housing Name", "Housing Price", "Housing Type", "Housing ID", "Location"
            }
        ));
        jScrollPane3.setViewportView(tblHousing);

        jLabel1.setText("Client Name: ");

        jLabel2.setText("Housing Name:");

        jLabel3.setText("Housing ID");

        jLabel4.setText("Location");

        jLabel5.setText("Price");

        txtClientName.setEditable(false);

        txtHousingID.setEditable(false);

        txtLocation.setEditable(false);

        txtHousingPrice.setEditable(false);

        txtHousingName.setEditable(false);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSelectMother.setText("SelectMother");
        btnSelectMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectMotherActionPerformed(evt);
            }
        });

        btnHousing.setText("Select Housing");
        btnHousing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHousingActionPerformed(evt);
            }
        });

        jLabel6.setText("Mother Name: ");

        txtMotherName.setEditable(false);

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHousing)
                            .addComponent(btnSelectMother))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHousingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHousingID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHousingName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(167, 167, 167)
                                                .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))))))
                            .addComponent(jLabel3))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnSelectMother)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHousing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHousingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHousingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHousingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnBack1))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectMotherActionPerformed
        // TODO add your handling code here:
     int selectedRow = tblMother.getSelectedRow();
     
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select row!");
            return;
           
        }
    Mother mother = (Mother) tblMother.getValueAt(selectedRow, 0);
     txtClientName.setText(mother.getName());
    }//GEN-LAST:event_btnSelectMotherActionPerformed

    private void btnHousingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHousingActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblHousing.getSelectedRow();
     
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select row!");
            return;
           
        }
        HousingNames transportNames = (HousingNames) tblHousing.getValueAt(selectedRow, 0);
        txtHousingName.setText(transportNames.getHousingName());
        txtHousingID.setText(transportNames.getHousingID());
        txtHousingPrice.setText(String.valueOf(transportNames.getPrice()));
       txtLocation.setText(transportNames.getLocation());
    }//GEN-LAST:event_btnHousingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: int selectedRow = housingTable.getSelectedRow();
    int index = business.getMotherDirectory().getMotherIndex(txtClientName.getText());
        business.getMotherDirectory().getMotherList().get(index).setHouseName(txtHousingName.getText());
         business.getMotherDirectory().getMotherList().get(index).setHousePrice(txtHousingPrice.getText());
          business.getMotherDirectory().getMotherList().get(index).setHouseStatus("Bought");
             
                 int index1 = business.getMotherDirectory().getMotherIndex(txtMotherName.getText());
                    business.getMotherDirectory().getMotherList().get(index1).setHouseName(txtHousingName.getText());
         business.getMotherDirectory().getMotherList().get(index1).setHousePrice(txtHousingPrice.getText());
          business.getMotherDirectory().getMotherList().get(index1).setHouseStatus("Bought"); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnHousing;
    private javax.swing.JButton btnSelectMother;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable tblHousing;
    private javax.swing.JTable tblMother;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtHousingID;
    private javax.swing.JTextField txtHousingName;
    private javax.swing.JTextField txtHousingPrice;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMotherName;
    // End of variables declaration//GEN-END:variables
}
