/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryManager;

import Business.Catalog.Disease;
import Business.Catalog.DiseaseCatalog;
import Business.Catalog.Vaccine;
import Business.Catalog.VaccineCatalog;
import javax.swing.JPanel;
import Business.Catalog.DiseaseCatalog;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class GiveVaccineNames extends javax.swing.JPanel {

    /**
     * Creates new form GiveVaccineNames
     */
    JPanel userProcessContainer;
   private EcoSystem business;
    private Organization organization;
    private Enterprise enterprise;
    private OrganizationDirectory organizationDir;
  public  GiveVaccineNames(JPanel userProcessContainer,EcoSystem business,Enterprise enterprise) {
      initComponents();
      this.userProcessContainer=userProcessContainer;
      this.business = business;
      this.organization=organization;
      this.enterprise = enterprise;
      this.organizationDir = organizationDir; 
        populateVacTable();
       
       
    }
   
   
   
 public void populateVacTable(){
     
        DefaultTableModel model = (DefaultTableModel) tblVac.getModel();

        model.setRowCount(0);
        for(Vaccine vaccine : business.getVaccineCatalog().getVaccineList()){
            Object[] row = new Object[1];
            row[0] = vaccine;
            //row[1] = vaccine.getQuantity();
            model.addRow(row);
        }
    }
   public void  populateEntVacTable(){
            
         DefaultTableModel model = (DefaultTableModel) tblEntVac.getModel();

        model.setRowCount(0);
         for(Network net: business.getNetworkList()){
          for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()){
              if(ent.getName().equals(enterprise.getName())){
                  Object[] row = new Object[3];
                  row[0]=ent.getName();
                 row[1] = ent.getVacName();
                 row[2] = ent.getQuantity();
                 model.addRow(row);
              }}}}
        
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuan = new javax.swing.JButton();
        btnSetValue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVac = new javax.swing.JTable();
        btnVaccine = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEntVac = new javax.swing.JTable();

        btnQuan.setText("Set Quantity of Vaccines");
        btnQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanActionPerformed(evt);
            }
        });

        btnSetValue.setText("Set Quantity");
        btnSetValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetValueActionPerformed(evt);
            }
        });

        tblVac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vac Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVac);
        if (tblVac.getColumnModel().getColumnCount() > 0) {
            tblVac.getColumnModel().getColumn(0).setResizable(false);
        }

        btnVaccine.setText("See Vaccines");
        btnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineActionPerformed(evt);
            }
        });

        tblEntVac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Vaccines", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEntVac);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVaccine)
                                .addGap(40, 40, 40)
                                .addComponent(btnSetValue)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVaccine)
                    .addComponent(btnSetValue))
                .addGap(91, 91, 91)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanActionPerformed
        // TODO add your handling code here:
                

    }//GEN-LAST:event_btnQuanActionPerformed

    private void btnSetValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetValueActionPerformed
        // TODO add your handling code here:private String name;
        int selectedRow =tblVac.getSelectedRow();
        if(selectedRow>=0){
            
        Vaccine v = (Vaccine)tblVac.getValueAt(selectedRow, 0);
        
        Update update = new Update(userProcessContainer,business,v,enterprise);
        userProcessContainer.add("update", update);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select any row");
        }
      
    }//GEN-LAST:event_btnSetValueActionPerformed

    private void btnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineActionPerformed
        // TODO add your handling code here:
         populateEntVacTable();  
        
    }//GEN-LAST:event_btnVaccineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuan;
    private javax.swing.JButton btnSetValue;
    private javax.swing.JButton btnVaccine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblEntVac;
    private javax.swing.JTable tblVac;
    // End of variables declaration//GEN-END:variables
}
