/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalTrackerRole;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Mother.Child;
import Business.Network.Network;
import Business.Organization.HospitalTrackerOrganization;
import Business.UserAccount.UserAccount;
import Business.VaccinationTrackerWorkQueue.HospitalTrackerWorkRequest;
import Business.VaccinationTrackerWorkQueue.VaccinationTrackerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nupur
 */
public class HospitalTrackerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalTrackerWorkAreaJPanel
     */
    JPanel userProcessContainer; UserAccount account; HospitalTrackerOrganization hospitalTrackerOrganization;Enterprise enterprise; Ecosystem business;
    public HospitalTrackerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, HospitalTrackerOrganization hospitalTrackerOrganization, Enterprise enterprise, Ecosystem business) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.hospitalTrackerOrganization=hospitalTrackerOrganization;
       this.enterprise=enterprise;
       this.business=business;
      populateRequestTable45();
    }
 
public void populateRequestTable45() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (VaccinationTrackerWorkRequest request1 : hospitalTrackerOrganization.getVaccinationTrackerWorkQueue().getWorkRequestListV()) {

           
                Object[] row = new Object[8];

                row[0] = request1;
                row[1] = request1.getmName();
                row[2] = request1.getBabyName();
                row[3] = request1.gethName();
                row[4] = request1.getSender();
                row[5] = request1.getReceiver();
                row[6] = request1.getStatus();
                String result1 = ((HospitalTrackerWorkRequest) request1).getVaccResult();
                row[7] = result1 == null ? "Waiting" : result1;
                model.addRow(row);
            }

        }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        processJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Mother name", "Child Name", "Hospital Name", "Sender", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(processJButton)
                        .addGap(18, 18, 18)
                        .addComponent(assignJButton)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processJButton)
                    .addComponent(assignJButton))
                .addContainerGap(335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        HospitalTrackerWorkRequest request = (HospitalTrackerWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ProcessHospitalTrackerRequestJPanel  ProcessHospitalTrackerRequestJPanel= new ProcessHospitalTrackerRequestJPanel(userProcessContainer, request);
        userProcessContainer.add(" ProcessHospitalTrackerRequestJPanel", ProcessHospitalTrackerRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        VaccinationTrackerWorkRequest request = (VaccinationTrackerWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Pending");
        populateRequestTable45();
    }//GEN-LAST:event_assignJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
